apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqloprtr-role

rules:
- apiGroups: ["otus.homework"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
#  resources: ["deployments", "deployments/status", "deployments/scale", "statefulsets", "statefulsets/status"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]