apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "mysqls.otus.homework"
spec:
  group: "otus.homework"
  versions:
    - name: "v1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              properties:
                image: 
                  type: string
                database: 
                  type: string
                password: 
                  type: string
                storage_size:
                  type: string
  scope: "Namespaced"
  names:
    plural: "mysqls"
    singular: "mysql"
    kind: "MySQL"
