# Этап 1: Сборка
FROM alpine:latest AS builder

RUN apk add --no-cache \
    build-base \
    pcre-dev \
    zlib-dev \
    openssl-dev \
    wget \
    linux-headers

# Версии компонентов
ENV NGINX_VERSION=1.29.4
ENV PCRE_VERSION=8.45
ENV ZLIB_VERSION=1.3.1

WORKDIR /src

# Скачиваем Nginx, PCRE (v1) и zlib

RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
    && tar -xvf nginx-${NGINX_VERSION}.tar.gz \
    && rm nginx-${NGINX_VERSION}.tar.gz

WORKDIR /src/nginx-${NGINX_VERSION}

# Конфигурируем со статическими путями к исходникам библиотек
# Флаги --with-pcre и --with-zlib заставят Nginx вкомпилировать их ВНУТРЬ бинарника
RUN ./configure \
    --prefix=/usr/share/nginx \
    --sbin-path=/usr/sbin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --with-http_stub_status_module \
    && make -j$(nproc) \
    && make install

# Этап 2: Финальный образ
FROM alpine:latest


RUN apk add --no-cache pcre zlib

# Копируем бинарник и конфиги
COPY --from=builder /usr/sbin/nginx /usr/sbin/nginx
COPY --from=builder /etc/nginx /etc/nginx

# Создаем директории для работы
RUN mkdir -p /var/log/nginx /var/cache/nginx /var/lib/nginx/tmp
# Проверка библиотек (поможет увидеть ошибку при сборке, если она осталась)
RUN ldd /usr/sbin/nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
