apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  namespace: homework
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      label: nginx-monitoring-service
  namespaceSelector:
    matchNames:
      - homework
  
  endpoints:
  - targetPort: metrics   # Номер порта в объекте Service  - 9113
    path: /metrics
    interval: 30s
    scheme: http
