apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-reader
  namespace: homework
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]

#- apiGroups: [""]
#  resources: ["pods/proxy"] # Allows access to the proxy subresource
#  verbs: ["get"]