apiVersion: rbac.authorization.k8s.io/v1beta
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: vault
roleref:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
    name: vault-auth
    namespace: default