apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
  labels: 
    user: Schneider.Alex
    task: Homework.1
    course: Kubernetes-platform
    university: Otus
    executionDate: 15.11.2025
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: sharedcatalog
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command:
          - rm /homework/index.html  
  initContainers:
  - name: nginx-init
    image: busybox:latest
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - https://line-mode.cern.ch/www/hypertext/WWW/TheProject.html
    volumeMounts:
    - name: sharedcatalog
      mountPath: /init
  volumes:
  - name: sharedcatalog
    emptyDir: {}
